version: '3'
services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - redis
    networks:
      - laravel-network

  redis:
    image: redis:latest
    networks:
      - laravel-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/default.conf
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge